# Generated by Django 3.0.8 on 2021-02-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('image_url', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
